name: flutter_project_template
description: A new Flutter project.
#com.matryal.seller
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shimmer: ^3.0.0
  badges: ^3.1.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  file_picker: ^8.0.3
  image_picker: ^1.1.2
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5
  # flutter_quill: ^11.4.1
  html_editor_enhanced: ^2.6.0
  #flutter pub run easy_localization:generate -S "assets/translations" -O "lib/core/localization"
  #flutter pub run easy_localization:generate -S "assets/translations" -O "lib/core/localization" -o "locale_keys.g.dart" -f keys
  easy_localization: ^3.0.7+1
  flutter_riverpod: ^2.6.1
  device_info_plus: ^11.4.0
  lottie: ^3.3.1
  dropdown_button2: ^2.3.9
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.1
  flutter_svg: ^2.1.0
  smooth_page_indicator: ^1.2.1
  fluentui_system_icons: ^1.1.273
  url_launcher: ^6.3.1
  pinput: ^5.0.1
  permission_handler: ^12.0.0+1
  awesome_drawer_bar: ^1.2.1
  card_swiper: ^3.0.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  curved_navigation_bar: ^1.0.6
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.6
  timeago: ^3.7.1
  fl_chart: ^1.0.0
  dotted_border: ^3.0.1


  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/svg/
    - assets/lottie/
    - assets/translations/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Saudi
      fonts:
        - asset: assets/fonts/saudi_riyal.ttf
          weight: 500

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix: 
  ignore_comments: true
    




