// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "unAuthorizedText": "انتهت صلاحية الجلسة",
  "tryAgain": "إعادة المحاولة",
  "serverText": "حدث خطأ ما اثناء معالجة طلبك",
  "socketText": "لايوجد اتصال بالانترنت",
  "timeoutText": "يبدو أن الخادم يستغرق وقتًا طويلاً للاستجابة، حاول مجدداً بعد فترة",
  "formatText": "تعذر إتمام العملية في الوقت الحالي.",
  "loadingText": "انتظر من فضلك",
  "loaded": "تم التحميل",
  "noData": "لاتوجد بيانات لعرضها",
  "appName": "THKEL",
  "search": "البحث",
  "mandatoryTx": "هذا الحقل مطلوب",
  "description": "التفاصيل (اختياري)",
  "invalidEmail": "البريد الالكتروني غير صالح",
  "confirmDelete": "هل انت متاكد من اكمال عملية الحذف؟",
  "confirmLogOut": "هل انت متاكد من اكمال عملية تسجيل الخروج؟",
  "confirmOperation": "هل انت متاكد من اكمال الاجراء؟",
  "confirmDeleteAccount": "هل انت متاكد من اكمال عملية حذف الحساب، سوف يؤدي ذلك الي حذف جميع سجلاتك السابقة؟",
  "deleteAccountHint": "نحن حزينون جدا لمغادرتك ونتمنى رؤيتك مجددا",
  "info": "معلومات",
  "delete": "حذف",
  "deleteMyAccount": "احذف حسابي",
  "change": "تغيير",
  "yes": "نعم",
  "no": "لا",
  "cancel": "إلغاء",
  "select": "اختيار",
  "selectDate": "اختر التاريخ",
  "listError": "هذه القائمة غير متوفرة حاليا",
  "projects": "الرئيسية",
  "profile": "الحساب",
  "notification": "الاشعارات",
  "warning": "تنبيه",
  "confirmation": "تأكيد العملية",
  "success": "نجاح العملية",
  "successSubText": "تمت العملية بنجاح",
  "error": "حدث خطأ",
  "okay": "حسنًا",
  "price": "السعر",
  "add": "إضافة",
  "optional": "اختياري",
  "selectImage": "عليك اختيار صورة واحدة على الأقل",
  "editProfile": "تعديل الملف الشخصي",
  "darkMode": "الوضع المظلم",
  "support": "اتصل بنا",
  "logOut": "تسجيل الخروج",
  "micPermission": "تفعيل إذن المايكروفون",
  "micPermissionMessage": "يجب تفعيل إذن الميكروفون لاستخدام هذه الميزة. الرجاء تفعيل الإذن من الإعدادات.",
  "imageReachedLimit": "حجم الصورة يجب أن لا يزيد عن 1 ميجابايت",
  "accessImage": "التطبيق يحتاج إلى إذن لعرض الصور، فعل الإذن من الإعدادات.",
  "onboardingTitle1": "حجز سهل",
  "onboardingTitle2": "تتبع شحنتك بدقة",
  "onboardingTitle3": "\"ثقيل\" للشحن السريع",
  "onboardingSubTitle1": "احجز خدمة الشحن الثقيل الخاصة بك في دقائق مع الدفع الآمن",
  "onboardingSubTitle2": "تتبع الشحنة الخاصة بك بدقة مع نظام تحديد المواقع (GPS) المتقدم لدينا",
  "onboardingSubTitle3": "نقل البضائع الثقيلة الخاصة بك بأمان وبسرعة في جميع أنحاء المملكة",
  "start": "ابدأ",
  "next": "التالي",
  "skip": "تخطي",
  "myPackage": "شحناتي",
  "subWelcome": "الوجهة عليك والثقل علينا",
  "offers": "العروض",
  "welcome": "يا هلا ومرحبا",
  "trackYourCargo": "تتبع شحنتك",
  "trackCargo": "تتبع الشحنة",
  "enterCargoNumber": "ادخل رقم الشحنة",
  "serviceTitle": "ثقيل يوصّل",
  "appService": "خدماتنا",
  "serviceSubTitle": "شحن مضمون وسريع، يوصلها لك وين ما تبي",
  "bookingNow": "احجز الآن",
  "booking": "طلب جديد",
  "bookingDetails": "تفاصيل الشحنة",
  "selectLocation": "تحديد الموقع",
  "previous": "السابق",
  "weight": "وزن الشحنة",
  "materialStatus": "نوع النقل",
  "materialType": "نوع الحمولة",
  "vehicleCategories": "نوع الشاحنة",
  "vehicleSubCategories": "فئة الشاحنة",
  "ton": "طن",
  "kilogram": "كيلو",
  "quickBooking": "حجز سريع",
  "deliveryPoint": "نقطة التسليم",
  "pickupPoint": "نقطة الاستلام",
  "scheduledBooking": "حجز مجدول",
  "unit": "الوحدة",
  "pickUpLocation": "نقطة الاستلام",
  "destinationLocation": "نقطة التسليم",
  "enableLocation": "خدمة الموقع غير مفعلة. يرجى تفعيلها من الإعدادات.",
  "selectTime": "اختر التوقيت",
  "invalidFormat": "إدخال غير صالح! يجب إدخال أرقام فقط.",
  "invalidNumber": "رقم غير صالح! يرجى إدخال رقم صحيح.",
  "maxTonLimit": "الحد الأقصى المسموح به هو 40 طن!",
  "maxKiloLimit": "الحد الأقصى المسموح به هو 999 كيلو!",
  "minValueError": "الحد الأدنى المسموح به هو 1.",
  "selectBookingType": "الرجاء اختيار نوع الحجز",
  "userLocation": "حدد موقعي",
  "accept": "قبول",
  "reject": "رفض",
  "rs": "ر.س ",
  "cargo": "شحنة",
  "from": "من",
  "to": "الى",
  "cargoDetails": "تفاصيل الشحنة",
  "dry": "جاف",
  "cold": "بارد",
  "truckStatus": "مسار الشحنة",
  "senderInfo": "معلومات المرسل",
  "senderName": "اسم المرسل",
  "senderPhone": "رقم جوال المرسل",
  "receiverInfo": "معلومات المستلم",
  "receiverName": "اسم المستلم",
  "receiverPhone": "رقم جوال المستلم",
  "goToOffers": "الانتقال الى قسم العروض",
  "edit": "تعديل",
  "myPocket": "محفظتي",
  "language": "اللغة",
  "security": "إعدادات الأمان",
  "deleteAccount": "حذف الحساب",
  "changePassword": "تغيير كلمة المرور",
  "changePhoneNumber": "تغيير رقم الهاتف",
  "needHelp": "تحتاج مساعدة؟",
  "commandQuestion": "الأسئلة الشائعة",
  "report_items": "الشروط والأحكام",
  "login": "تسجيل الدخول",
  "register": "إنشاء حساب",
  "arabicOrEnglishOnlyValidation": "الرجاء إدخال الحروف العربية أو الإنجليزية فقط",
  "invalidPhone": "رقم الجوال غير صالح",
  "noMoreThan14": "يجب أن لا يكون الاسم أكثر من 30 خانات",
  "noteMoreThan14": "يجب أن لا تكون التفاصيل أكثر من 100 خانات",
  "notStart0": "يجب أن يبدأ الرقم بـ 5",
  "phone": "رقم الجوال",
  "name": "الاسم",
  "email": "البريد الإلكتروني",
  "verifyPhone": "إدخال رمز OTP",
  "codeDidNotArrive": "لم يصل الرمز؟ طلب رمز جديد",
  "verify": "تحقق",
  "backToLogin": "رجوع إلى الخلف",
  "fillAll": "يرجى إدخال رمز التحقق الكامل",
  "verifyPhoneText": "قم بإدخال رمز التحقق المرسل عبر رسالة نصية",
  "password": "كلمة المرور",
  "noLessThan": "الحد الأدنى 6 خانات",
  "confirmPassword": "تأكيد كلمة المرور",
  "passwordNotMatch": "كلمة المرور غير متطابقة",
  "registerSuccess": "تم إنشاء حساب بنجاح قم بتسجيل الدخول",
  "resendOtp": "تم إعادة إرسال رمز التحقق",
  "searchLocation": "البحث عن الموقع",
  "selectOnMap": "التحديد على الخريطة",
  "searchHistory": "سجل البحث",
  "confirmPickupLocation": "تأكيد موقع الاستلام",
  "confirmDestinationLocation": "تأكيد موقع التسليم",
  "confirm": "تأكيد",
  "confirmFilling": "يرجى ملء جميع الحقول المطلوبة بشكل صحيح",
  "confirmEnterData": "تأكد من إدخال وزن الشحنة ونوع الوزن",
  "noTrack": "عذرًا، لا توجد شاحنات متاحة تطابق الخيارات المحددة. يرجى تعديل البيانات أو المحاولة لاحقًا",
  "requiredLogin": "يرجى تسجيل الدخول أولاً للمتابعة",
  "requiredLoginHint": "يرجى تسجيل الدخول أولاً للتمتع بالمزايا",
  "saveChanges": "تحديث البيانات",
  "changePasswordHint": "لحماية حسابك، يُفضل تحديث كلمة المرور بانتظام. اختر كلمة مرور قوية تحتوي على أحرف وأرقام ورموز.",
  "changePhoneNumberHint": "رقم الهاتف يُستخدم لتأمين حسابك واستعادة الوصول عند الحاجة. تأكد من إدخال رقم صحيح ومفعل.",
  "deleteAccountMessage": "هل أنت متأكد أنك تريد حذف حسابك؟ سيؤدي ذلك إلى حذف جميع بياناتك بشكل دائم.",
  "sessionExpired": "انتهت صلاحية الجلسة، الرجاء تسجيل الدخول مجددًا.",
  "nationalId": "رقم الهوية (اختياري)",
  "updateProfileSuccess": "تم تحديث البيانات بنجاح، شكراً",
  "rejectPermission": "تم رفض إذن الوصول للموقع الحالي",
  "bookingTime": "توقيت الحجز",
  "quickBookingMessage": "حجز خلال 24 ساعة",
  "trackType": "نوع الشاحنة",
  "maxWeight": "الحمولة القصوى",
  "withTax": "شامل الضريبة",
  "awaitData": "جاري استقبال العروض",
  "offerMessage": "جاري استقبال العروض. ويرجى قبول أحد العروض خلال المدة المتبقية",
  "timerOver": "انتهت المهلة المحددة لقبول أحد العروض المتاحة.\nيرجى تمديد الوقت لقبول عرض جديد، أو إلغاء الشحنة إذا لم تعد هناك حاجة لها",
  "extend": "تمديد",
  "chooseLocation": "اختر الموقع",
  "chooseLocationFromMap": "اختيار الموقع على الخريطة",
  "deleteLocation": "حذف الموقع",
  "deleteLocationContent": "هل أنت متأكد أنك تريد حذف هذا الموقع؟ سيؤدي ذلك إلى حذف الموقع بشكل دائم.",
  "senderDetails": "تفاصيل المرسل",
  "receiverDetails": "تفاصيل المستقبل",
  "hideDetails": "إخفاء التفاصيل",
  "showDetails": "عرض التفاصيل",
  "sameLocationError": "الرجاء اختيار موقع التسليم والاستلام مختلفين",
  "enterSenderName": "أدخل اسم المرسل",
  "enterReceiverName": "أدخل اسم المستقبل",
  "enterSenderAddress": "أدخل عنوان المرسل",
  "enterReceiverAddress": "أدخل عنوان المستقبل",
  "enterSenderPhone": "أدخل رقم جوال المرسل",
  "enterReceiverPhone": "أدخل رقم جوال المستقبل",
  "senderHintText": "يرجى إدخال بيانات المرسل بدقة لتتمكن شركة التوصيل من استلام الشحنة دون تأخير",
  "receiverHintText": "يرجى إدخال بيانات المستقبل لضمان توصيل الشحنة إلى العنوان الصحيح",
  "addressError": "أوه! ما قدرنا نحدد العنوان حالياً، جرب مرة ثانية.",
  "defaultAddress": "المملكة العربية السعودية",
  "noSavedLocations": "لا يوجد مواقع محفوظة",
  "theme": "الوضع الليلي"
};
static const Map<String,dynamic> _en = {
  "unAuthorizedText": "Session expired",
  "tryAgain": "Try Again",
  "serverText": "An error occurred while processing your request",
  "socketText": "No internet connection",
  "timeoutText": "It seems the server is taking too long to respond. Please try again later",
  "formatText": "Unable to complete the operation at this time.",
  "loadingText": "Please wait",
  "loaded": "Loaded",
  "noData": "No data available to display",
  "appName": "THKEL",
  "search": "Search",
  "mandatoryTx": "This field is required",
  "description": "Description (optional)",
  "invalidEmail": "Invalid email",
  "confirmDelete": "Are you sure you want to complete the deletion process?",
  "confirmLogOut": "Are you sure you want to log out?",
  "confirmOperation": "Are you sure you want to proceed with the operation?",
  "confirmDeleteAccount": "Are you sure you want to delete your account? This will remove all your previous records.",
  "deleteAccountHint": "We are really sad to see you go, and we hope to see you again.",
  "info": "Info",
  "delete": "Delete",
  "deleteMyAccount": "Delete my account",
  "change": "Change",
  "yes": "Yes",
  "no": "No",
  "cancel": "Cancel",
  "select": "Select",
  "selectDate": "Select Date",
  "listError": "This list is currently unavailable",
  "projects": "Home",
  "profile": "Profile",
  "notification": "Notifications",
  "warning": "Warning",
  "confirmation": "Confirmation",
  "success": "Operation Successful",
  "successSubText": "Operation completed successfully",
  "error": "An error occurred",
  "okay": "Okay",
  "price": "Price",
  "add": "Add",
  "optional": "Optional",
  "selectImage": "You must select at least one image",
  "editProfile": "Edit Profile",
  "darkMode": "Dark Mode",
  "support": "Contact Us",
  "logOut": "Log Out",
  "micPermission": "Enable Microphone Permission",
  "micPermissionMessage": "Microphone permission is required to use this feature. Please enable it in the settings.",
  "imageReachedLimit": "Image size must not exceed 1MB",
  "accessImage": "The app requires permission to display images. Please enable the permission in the settings.",
  "onboardingTitle1": "Easy Booking",
  "onboardingTitle2": "Track Your Cargo Precisely",
  "onboardingTitle3": "\"Thakil\" for fast shipping",
  "onboardingSubTitle1": "Book your heavy cargo service in minutes with secure payment",
  "onboardingSubTitle2": "Track your cargo precisely with our advanced GPS system",
  "onboardingSubTitle3": "Transport your heavy goods safely and quickly throughout the kingdom",
  "start": "Start",
  "next": "Next",
  "skip": "Skip",
  "myPackage": "My Packages",
  "subWelcome": "Your destination, our load",
  "offers": "Offers",
  "welcome": "Welcome",
  "trackYourCargo": "Track Your Cargo",
  "trackCargo": "Track Cargo",
  "enterCargoNumber": "Enter Cargo Number",
  "serviceTitle": "Thakil Delivers",
  "appService": "Our Services",
  "serviceSubTitle": "Guaranteed and fast shipping, we deliver wherever you need",
  "bookingNow": "Book Now",
  "booking": "New Order",
  "bookingDetails": "Cargo Details",
  "selectLocation": "Select Location",
  "previous": "Previous",
  "weight": "Cargo Weight",
  "materialStatus": "Transport Type",
  "materialType": "Cargo Type",
  "vehicleCategories": "Truck Type",
  "vehicleSubCategories": "Truck Subtype",
  "ton": "Ton",
  "kilogram": "Kg",
  "quickBooking": "Quick Booking",
  "deliveryPoint": "Delivery Point",
  "pickupPoint": "Pickup Point",
  "scheduledBooking": "Scheduled Booking",
  "unit": "Unit",
  "pickUpLocation": "Pickup Location",
  "destinationLocation": "Destination Location",
  "enableLocation": "Location service is not enabled. Please enable it in settings.",
  "selectTime": "Select Time",
  "invalidFormat": "Invalid input! Please enter numbers only.",
  "invalidNumber": "Invalid number! Please enter a valid number.",
  "maxTonLimit": "The maximum allowed is 40 tons!",
  "maxKiloLimit": "The maximum allowed is 999 kg!",
  "minValueError": "The minimum allowed is 1.",
  "selectBookingType": "Please select a booking type",
  "userLocation": "Use My Location",
  "accept": "Accept",
  "reject": "Reject",
  "rs": "SAR ",
  "cargo": "Cargo",
  "from": "From",
  "to": "To",
  "cargoDetails": "Cargo Details",
  "dry": "Dry",
  "cold": "Cold",
  "truckStatus": "Cargo Status",
  "senderInfo": "Sender Info",
  "senderName": "Sender Name",
  "senderPhone": "Sender Phone Number",
  "receiverInfo": "Receiver Info",
  "receiverName": "Receiver Name",
  "receiverPhone": "Receiver Phone Number",
  "goToOffers": "Go to Offers Section",
  "edit": "Edit",
  "myPocket": "My Wallet",
  "language": "Language",
  "security": "Security Settings",
  "deleteAccount": "Delete Account",
  "changePassword": "Change Password",
  "changePhoneNumber": "Change Phone Number",
  "needHelp": "Need Help?",
  "commandQuestion": "FAQs",
  "report_items": "Terms & Conditions",
  "login": "Login",
  "register": "Sign Up",
  "arabicOrEnglishOnlyValidation": "Please enter only Arabic or English letters",
  "invalidPhone": "Invalid phone number",
  "noMoreThan14": "Name must not exceed 30 characters",
  "noteMoreThan14": "Details must not exceed 100 characters",
  "notStart0": "Number must start with 5",
  "phone": "Phone Number",
  "name": "Name",
  "email": "Email",
  "verifyPhone": "Enter OTP Code",
  "codeDidNotArrive": "Didn’t receive the code? Request a new one",
  "verify": "Verify",
  "backToLogin": "Back to Login",
  "fillAll": "Please fill in the full verification code",
  "verifyPhoneText": "Please enter the OTP code sent via SMS",
  "password": "Password",
  "noLessThan": "At least 6 characters",
  "confirmPassword": "Confirm Password",
  "passwordNotMatch": "Passwords do not match",
  "registerSuccess": "Account created successfully. Please login",
  "resendOtp": "Resend OTP",
  "searchLocation": "Search Location",
  "selectOnMap": "Select on Map",
  "searchHistory": "Search History",
  "confirmPickupLocation": "Confirm Pickup Location",
  "confirmDestinationLocation": "Confirm Destination Location",
  "confirm": "Confirm",
  "confirmFilling": "Please fill out all required fields correctly",
  "confirmEnterData": "Ensure cargo weight and type are entered correctly",
  "noTrack": "Sorry, no trucks available matching your selection. Please adjust your input or try later",
  "requiredLogin": "Please log in to proceed",
  "requiredLoginHint": "Log in to enjoy the benefits",
  "saveChanges": "Save Changes",
  "changePasswordHint": "To secure your account, we recommend updating your password regularly. Choose a strong password with letters, numbers, and symbols.",
  "changePhoneNumberHint": "Your phone number is used to secure your account and restore access when needed. Please ensure you enter a correct and active number.",
  "deleteAccountMessage": "Are you sure you want to delete your account? This will permanently remove all your data.",
  "sessionExpired": "Session expired. Please log in again.",
  "nationalId": "National ID (Optional)",
  "updateProfileSuccess": "Profile updated successfully, Thank you",
  "rejectPermission": "Location permission denied",
  "bookingTime": "Booking Time",
  "quickBookingMessage": "Booking within 24 hours",
  "trackType": "Truck Type",
  "maxWeight": "Max Weight",
  "withTax": "Including Tax",
  "awaitData": "Receiving offers",
  "offerMessage": "Receiving offers. Please accept one of the offers within the remaining time",
  "timerOver": "The time limit to accept available offers has expired. Please extend the time to accept a new offer or cancel the shipment if no longer needed",
  "extend": "Extend",
  "chooseLocation": "Choose Location",
  "chooseLocationFromMap": "Choose location on map",
  "deleteLocation": "Delete Location",
  "deleteLocationContent": "Are you sure you want to delete this location? This will permanently remove the location.",
  "senderDetails": "Sender Details",
  "receiverDetails": "Receiver Details",
  "hideDetails": "Hide Details",
  "showDetails": "Show Details",
  "sameLocationError": "Please select different pickup and delivery locations",
  "enterSenderName": "Enter sender name",
  "enterReceiverName": "Enter receiver name",
  "enterSenderAddress": "Enter sender address",
  "enterReceiverAddress": "Enter receiver address",
  "enterSenderPhone": "Enter sender phone number",
  "enterReceiverPhone": "Enter receiver phone number",
  "senderHintText": "Please enter sender details accurately to avoid delay in pickup",
  "receiverHintText": "Please enter receiver details to ensure correct delivery",
  "addressError": "Oops! We couldn’t find the address right now, please try again.",
  "defaultAddress": "Kingdom of Saudi Arabia",
  "noSavedLocations": "No saved locations",
  "theme": "Dark Mode"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
